# Generated by Django 5.2.1 on 2025-05-27 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VenomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('non-venomous', 'Non-Venomous'), ('mildly-venomous', 'Mildly-Venomous'), ('moderately-venomous', 'Moderately-Venomous'), ('deadly-venomous', 'Deadly-Venomous')], max_length=50)),
                ('effect_description', models.TextField()),
                ('description_translation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('description_translation', models.TextField(blank=True, null=True)),
                ('danger_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], default='low', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='snakes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_in', models.ManyToManyField(blank=True, related_name='snakes', to='webapp.region')),
                ('is_venomous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.venomtype')),
            ],
        ),
    ]
